@startuml uc_A2
!pragma layout smetana
skinparam dpi 220
skinparam shadowing false
left to right direction
skinparam usecase {
  BackgroundColor #FDF6E3
  BorderColor #B58900
}
actor "Người chơi" as P
actor "Agent AI" as AI
usecase "A2. Điều khiển xe tăng" as UC
P --> UC
UC ..> AI
@enduml
