@startuml uc_B7
!pragma layout smetana
skinparam dpi 220
skinparam shadowing false
left to right direction
skinparam usecase {
  BackgroundColor #FDF6E3
  BorderColor #B58900
}
actor "Chủ phòng\n(Host)" as Host
actor "Người tham gia\n(Client)" as Client
usecase "B7. Rời phòng / Huỷ kết nối" as UC
Host --> UC
Client --> UC
@enduml
