@startuml uc_groupB_internet
!pragma layout smetana
skinparam dpi 220
skinparam shadowing false
left to right direction
skinparam usecase {
  BackgroundColor #FDF6E3
  BorderColor #B58900
}
actor "Chủ phòng\n(Host)" as Host
actor "Người tham gia\n(Client)" as Client
actor "Máy chủ\nRelay/PIBT" as Server

title Chơi nhiều người - Internet
rectangle " " as Sys {
  usecase "B3. Tạo phòng Internet" as B3
  usecase "B4. Tham gia phòng Internet" as B4
  usecase "B5. Phòng chờ & bắt đầu" as B5
  usecase "B6. Chơi mạng nhiều người" as B6
  usecase "B7. Rời phòng / Huỷ" as B7
}
Host --> B3
Client --> B4
Host --> B5
Client --> B5
Host --> B6
Client --> B6
Host --> B7
Client --> B7
B5 ..> B6 : <<include>>
B3 ..> Server
B4 ..> Server
B6 ..> Server
@enduml
